# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0023_merge_20180615_0825'),
        ('b3_organization', '0011_merge_20180416_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('feature', models.CharField(choices=[
                    ('new_checkout', 'New Checkout')],
                    help_text='Feature being switched/toggled',
                    max_length=32, verbose_name='Feature')),
                ('name', models.CharField(
                    help_text='Switch name',
                    max_length=128, verbose_name='Name')),
                ('active', models.BooleanField(
                    default=False, help_text='Is this switch active?',
                    verbose_name='Active')),
                ('note', models.TextField(
                    blank=True,
                    help_text='Switch description',
                    verbose_name='Note')),
                ('creation_date', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Date when this Switch was created.',
                    verbose_name='Created')),
                ('last_modified', models.DateTimeField(
                    auto_now=True,
                    help_text='Date when this Switch was last modified.',
                    verbose_name='Last Modified')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='switches',
                    to='b3_organization.Organization',
                    verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together=set([('organization', 'feature')]),
        ),
    ]
