# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0003_sync_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_checkout', 'New Checkout'), ('new_payment_methods', 'New Payment Methods')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
