# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0003_sync_addresses'),
    ]

    operations = []
