# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0004_auto_20180724_1515'),
        ('b3_migration', '0005_migrate_payment_methods'),
    ]

    operations = [
    ]
