# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0007_auto_20180726_1156'),
    ]

    operations = []
