# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0008_shippingmethodbuddy'),
    ]

    operations = []
