# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0010_auto_20180829_1417'),
    ]

    operations = []
