# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 09:55
from __future__ import unicode_literals

import apps.b3_core.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0012_migrate_orders'),
    ]

    operations = []
