# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-13 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0013_auto_20180912_0955'),
    ]

    operations = []
