# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


def delete_switches(apps, schema_editor):
    Switch = apps.get_model('b3_migration', 'switch')
    for switch in Switch.objects.all():
        if switch.feature in ['new_pricing', 'new_payment_methods']:
            switch.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0014_sync_order_actions'),
    ]

    operations = [
        migrations.RunPython(delete_switches, migrations.RunPython.noop, atomic=True),
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_checkout', 'New Checkout')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
