# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0015_auto_20180926_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_checkout', 'New Checkout'), ('new_user_panel', 'New UserPanel'), ('left_navigation', 'Left Navigation')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
