# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0018_auto_20181206_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_user_panel', 'New UserPanel'), ('new_basket', 'New Basket')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
