# Generated by Django 2.1.8 on 2019-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0019_add_new_basket_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_user_panel', 'New UserPanel'), ('new_basket', 'New Basket'), ('sales_transaction', 'Sales Transaction')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
