# Generated by Django 2.1.8 on 2019-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3_migration', '0020_auto_20190709_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='feature',
            field=models.CharField(choices=[('new_user_panel', 'New UserPanel'), ('new_basket', 'New Basket'), ('sales_transaction', 'Sales Transaction'), ('enable_basket_part_requirements', 'Enable Basket Part Requirements')], help_text='Feature being switched/toggled', max_length=32, verbose_name='Feature'),
        ),
    ]
